version: "3.9"

services:
  app:
    build: .
    container_name: spring-boot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/test_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      LOGSTASH_HOST: logstash:5600     # ✅ Gửi log tới container logstash
      JAVA_OPTS: "-XX:ActiveProcessorCount=2 -Xms512m -Xmx1024m"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - logstash
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 2G
    networks:
      - my_network

  postgres:
    image: postgres:17-alpine
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: test_db
    ports:
      - "5686:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: 1G
    networks:
      - my_network

  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    container_name: elasticsearch
    restart: always
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 2G
    networks:
      - my_network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.1
    container_name: kibana
    restart: always
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic-search:9200
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: 1G
    networks:
      - my_network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.14.1
    container_name: logstash
    restart: always
    ports:
      - "5600:5600"
      - "5044:5044"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      - LS_JAVA_OPTS=-Xms512m -Xmx512m
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: 1G
    networks:
      - my_network


volumes:
  postgres-data:

networks:
  my_network:
